### ISSUE TITLE
Failed to generate or install certificate!

### ISSUE THREAD

**Issue by brian-heidrich** [Miserlou/Zappa#1325]
When doing the zappa certify command for the first time I received the follow error:

Error registering: 400 {
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",
  "status": 400
}
Failed to generate or install certificate! :(

I ran pip install zappa --upgrade and after that the error still occurred. Manually changing the URL myself in the lets_encrypt.py file fixed the issue.

## Your Environment
* Zappa version used: 0.45.1

**Comment by Debetux** [comment]
This issue is fixed on master.
Zappa's pypi package seems to be out of date (uploaded on 2017-11-03).

**Comment by brian-heidrich** [comment]
I just went in and saw that myself, looks like it should be an easy fix then.

**Comment by Paradoxeuh** [comment]
Still an issue as pip install still delivers 0.45.1. It's so simple to correct it, can't believe it's been here for more than 3 months now.

**Comment by ivan770** [comment]
Got that error too, but found easy fix. Head to `your-python-venv/site-packages/zappa` and change line 242 to `"agreement": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",`

**Comment by scoates** [comment]
Related #1425
