### ISSUE TITLE
Package Error: python-dateutil

### ISSUE THREAD

**Issue by weasteam** [Miserlou/Zappa#1927]
Would you please support the newest version of python-dateutil?

```
ERROR: zappa 0.48.2 has requirement python-dateutil<2.7.0,>=2.6.1, but you'll have python-dateutil 2.8.0 which is incompatible.
```

**Comment by gonwi** [comment]
I am running with the same issue here. Also encountered problem with jmespath.
```
ERROR: zappa 0.48.2 has requirement jmespath==0.9.3, but you'll have jmespath 0.9.4 which is incompatible.
ERROR: zappa 0.48.2 has requirement python-dateutil<2.7.0,>=2.6.1, but you'll have python-dateutil 2.8.0 which is incompatible.
```

**Comment by kittylon** [comment]
I also have the same error for jmespath and python-dateutil, any news on this?

**Comment by thibaut-singlefile** [comment]
This is impacting us as well.

**Comment by jneves** [comment]
This is solved by #1998 which I hope to merge and release this week. And we should be done with pinned dependencies altogether.

**Comment by brianhelba** [comment]
@jneves Ping. Now that #1998 is merged and [`botocore` is not restricted to `python-dateutil<2.7.0`](https://github.com/boto/botocore/blob/3f744ed3a01b2ffaa96605996b102fcebd6b85e7/setup.py#L29), can the pinning of `python-dateutil` in Zappa be removed?

**Comment by hickeroar** [comment]
> This is solved by #1998 which I hope to merge and release this week. And we should be done with pinned dependencies altogether.
This is still an issue. I'm trying to convert an app that has multiple dependencies which require dateutil 2.8+ over to Zappa/Lambda, but I cannot because of this issue. Do we have any kind of ETA for when this will be fixed?

**Comment by jneves** [comment]
Not yet, haven't found the specific reason why it was locked in the first place. Will have to check if it's just some API change.

**Comment by tommie-lie** [comment]
I did some digging and found #1449 from times when requirements.txt still contained hard version dependencies. python-dateutil was pinned to 2.6, because botocore at the time still depended on <2.7. botocore has since removed the dependency on python-dateutil completely (c.f. botocore/botocore@7477a82b379b0e5b36e727a32002f554a4862d2e).

I also checked Zappas sourcecode, and dateutil is used only in cli.py to parse ISO timestamps. There are no breaking changes and all tests are still running with dateutil>2.8.

@jneves would you like a PR for loosening python-dateutil version?

**Comment by bmyrtil-smg** [comment]
Any update on this? Like everyone else, I am starting to run into issues because of the pinned version.

**Comment by amsal-muhammad** [comment]
Please update. My dependencies don't resolve due to this.

**Comment by jasonrhaas** [comment]
FYI there is a PR that is ready to be merged but is just sitting around.  I got around this issue but installing zappa directly off that branch.   The branch is `feature/updates-including-dateutil`.

In your virtualenv:

```
pip uninstall zappa
pip install git+https://github.com/Miserlou/Zappa.git@feature/updates-including-dateutil#egg=zappa
pip install -U python-dateutil
```

**Comment by jneves** [comment]
Thanks, will hopefully sort this out tomorrow.

**Comment by amsal-muhammad** [comment]
Please merge it :(

**Comment by jayfid** [comment]
Ran into this today too, but I'm unsure if I should wait for the release or attempt a different approach. Is something preventing this from being released?

**Comment by chris-erickson** [comment]
Add this instead until we get a real release.

`-e git+https://github.com/Miserlou/Zappa.git@0c8d99ddbc297124d93c166652013abba50ee86e#egg=zappa`

**Comment by louq-gharnati** [comment]
Running into this issue today too :(
