### ISSUE TITLE
Unable to resolve the cors for django project after deploying using zappa.

### ISSUE THREAD

**Issue by abdulwahid24** [Miserlou/Zappa#693]
## Context
Hey guys, 
I have designed a product with Django and now I wanted to put it in production and I am trying to use #zappa  but since last two weeks I am struggling to make it live on aws lambda but ending up with this error `XMLHttpRequest cannot load https://n055r69r43.execute-api.ap-southeast-1.amazonaws.com/dev/api-token-auth/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.` 

I tried everything to resolve the problem but couldn't succeed, I may required to move to manual process on aws ec2 if it doesn't work but I hope posting here will help me to resolve the issue.

 

## Expected Behavior

As per the documentation If we are setting cors enable then ideally we should not get cors error from any browser.

## Actual Behavior

Though we mentioned the cors settings in `zappa_settings.json` but still getting cors error.
![screen shot 2017-02-27 at 7 51 14 am](https://cloud.githubusercontent.com/assets/4718496/23346597/906fa70c-fcc1-11e6-918d-75ac6d1c3673.png)

## Steps to Reproduce

1. zappa init
2. Cors changes in zappa_settings.json 
3. zappa deploy/update dev

## Your Environment

* Zappa version used: zappa 0.37.1
* Operating System and Python version: Mac and Python 2.7
* Link to your project (optional):
* Your `zappa_settings.py`: 
Here is my `zappa_setttings.json`
```
{
    "dev": {
        "django_settings": "homejoy.settings", 
        "s3_bucket": "conjuror-cloud",
        "apigateway_enabled": true,
        "delete_local_zip": true,
        "log_level": "DEBUG",
        "method_header_types": [
          "accept",
          "accept-encoding",
          "content-type",
          "dnt",
          "origin",
          "user-agent",
          "x-csrftoken",
          "x-requested-with",
          "Location",
          "Status",
          "X-Frame-Options",
          "Set-Cookie",
          "Authorization",
          "Access-Control-Allow-Origin",
          "Access-Control-Allow-Headers",
          "Access-Control-Allow-Methods"
        ],
        "parameter_depth": 10,
        "keep_warm": true,
        "cors": true,
        "aws_region": "ap-southeast-1",
        "enable_cors": true
    }
}
```

Thanks,
Abdul Wahid

**Comment by Miserlou** [comment]
You may have luck settings `binary_support` to `false` for a brief time until we get this sorted out.

**Comment by Miserlou** [comment]
Possibly fixed in 0.37.2, let me know if not and I'll reopen.

**Comment by abdulwahid24** [comment]
@Miserlou I have investigated further and found that AWS CloudFront is rejecting the OPTION request though I have putted the `Allow-Control-Access-Origin` header in forward headers in cloudfront distribution. I have created a question [here](http://stackoverflow.com/questions/42528564/option-request-rejected-by-cloudfront) with detailed description.

**Comment by Miserlou** [comment]
Thanks for reporting, there is a discussion and temporary solution in https://github.com/Miserlou/Zappa/issues/699

**Comment by abdulwahid24** [comment]
@Miserlou The issue with preflight OPTION has been resolved by upgrading zappa version to `0.37.2` and adding `"binary_support" : false` into zappa_settings.json. Thanks a ton @Miserlou really appreciated.

**Comment by abdulwahid24** [comment]
@Miserlou I am facing an issue to upload an image file and it seems its because I have set the `binary_support` to `false` and I have seen your previous discussions regarding image upload issue where you said that to upload image `binary_support` should be set to `true`. 

Please let me know how can I resolve the issue now ?

**Comment by abdulwahid24** [comment]
@Miserlou What is the relation of binary_search with image upload and preflight option request ?

**Comment by abdulwahid24** [comment]
Issue has been resolved as per the discussion mentioned [here](https://github.com/Miserlou/Zappa/issues/699). Thanks

**Comment by shikarkhane** [comment]
I am still getting the following error : 
`XMLHttpRequest cannot load https://something.execute-api.eu-west-1.amazonaws.com/dev/user/. Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by ctippur** [comment]
This is happening with 0.48.2 as well.
Options request goes thro (pre flight) but POST returns 403.
