### ISSUE TITLE
Error loading psycopg2 module on Python 3.6 (when on Lambda)

### ISSUE THREAD

**Issue by nikbora** [Miserlou/Zappa#800]
## Context
Shiny new Zappa 0.41 and Python 3.6

Django==1.11
djangorestframework==3.6.2
psycopg2==2.6.1
zappa==0.41.0
...

## Expected Behavior

It works fine locally, but on Lambda the following happens:

```
[1492873312435] File "/var/task/django_zappa_app.py", line 20, in get_django_wsgi
[1492873312435] return get_wsgi_application()
[1492873312435] File "/var/task/django/core/wsgi.py", line 13, in get_wsgi_application
[1492873312435] django.setup(set_prefix=False)
[1492873312435] File "/var/task/django/__init__.py", line 27, in setup
[1492873312435] apps.populate(settings.INSTALLED_APPS)
[1492873312435] File "/var/task/django/apps/registry.py", line 108, in populate
[1492873312435] app_config.import_models()
[1492873312435] File "/var/task/django/apps/config.py", line 202, in import_models
[1492873312436] self.models_module = import_module(models_module_name)
[1492873312436] File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
[1492873312436] return _bootstrap._gcd_import(name[level:], package, level)
[1492873312436] File "<frozen importlib._bootstrap>", line 978, in _gcd_import
[1492873312436] File "<frozen importlib._bootstrap>", line 961, in _find_and_load
[1492873312436] File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
[1492873312436] File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
[1492873312436] File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[1492873312436] File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
[1492873312436] File "/var/task/django/contrib/auth/models.py", line 4, in <module>
[1492873312436] from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
[1492873312436] File "/var/task/django/contrib/auth/base_user.py", line 52, in <module>
[1492873312436] class AbstractBaseUser(models.Model):
[1492873312436] File "/var/task/django/db/models/base.py", line 124, in __new__
[1492873312436] new_class.add_to_class('_meta', Options(meta, app_label))
[1492873312436] File "/var/task/django/db/models/base.py", line 330, in add_to_class
[1492873312437] value.contribute_to_class(cls, name)
[1492873312437] File "/var/task/django/db/models/options.py", line 214, in contribute_to_class
[1492873312437] self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
[1492873312437] File "/var/task/django/db/__init__.py", line 33, in __getattr__
[1492873312437] return getattr(connections[DEFAULT_DB_ALIAS], item)
[1492873312437] File "/var/task/django/db/utils.py", line 211, in __getitem__
[1492873312437] backend = load_backend(db['ENGINE'])
[1492873312437] File "/var/task/django/db/utils.py", line 115, in load_backend
[1492873312437] return import_module('%s.base' % backend_name)
[1492873312437] File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
[1492873312437] return _bootstrap._gcd_import(name[level:], package, level)
[1492873312437] File "/var/task/django/db/backends/postgresql/base.py", line 25, in <module>
[1492873312437] raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
[1492873312437] django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: dynamic module does not define module export function (PyInit__psycopg)
[1492873312437] During handling of the above exception, another exception occurred:
[1492873312437] Traceback (most recent call last):
[1492873312437] File "/var/runtime/awslambda/bootstrap.py", line 466, in <module>
[1492873312437] main()
[1492873312437] File "/var/runtime/awslambda/bootstrap.py", line 462, in main
[1492873312438] handle_event_request(request_handler, invokeid, event_body, context_objs, invoked_function_arn)
[1492873312438] File "/var/runtime/awslambda/bootstrap.py", line 248, in handle_event_request
[1492873312438] result = to_json(result)
[1492873312438] File "/var/runtime/awslambda/bootstrap.py", line 224, in to_json
[1492873312438] return json.dumps(obj, default=decimal_serializer)
[1492873312438] File "/var/lang/lib/python3.6/json/__init__.py", line 238, in dumps
[1492873312438] **kw).encode(obj)
[1492873312438] File "/var/lang/lib/python3.6/json/encoder.py", line 199, in encode
[1492873312438] chunks = self.iterencode(o, _one_shot=True)
[1492873312438] File "/var/lang/lib/python3.6/json/encoder.py", line 257, in iterencode
[1492873312438] return _iterencode(o, 0)
[1492873312438] File "/var/runtime/awslambda/bootstrap.py", line 42, in decimal_serializer
[1492873312439] raise TypeError(repr(o) + " is not JSON serializable")
[1492873312439] TypeError: <FrameSummary file /var/task/handler.py, line 514 in lambda_handler> is not JSON serializable
[1492873312598] Error loading psycopg2 module: dynamic module does not define module export function (PyInit__psycopg)
ImproperlyConfigured
```

## Possible Fix

No idea yet, but before I dig further, I was wondering if someone had any pointers. I assume its something to do with pre-compiled C-extension packages not working on Python 3.6 yet.

**Comment by Miserlou** [comment]
> I assume its something to do with pre-compiled C-extension packages not working on Python 3.6 yet.

This is probably the case. I encourage you to dive in to try to solve this. Hopefully we can do this without recompiling everything.

Thanks for reporting!

Good luck on trying to solve this, please report back with your findings.

**Comment by nikbora** [comment]
Ok, so after some digging I reckon the best way to solve is two-fold:

**First**

Add support Python 3.6 manylinux wheels packages. I wrote the code and test here, will submit PR from https://github.com/Miserlou/Zappa/compare/master...nikbora:master.

**Then Either**

*A*: remove `pscyopg2` and `numpy` from https://github.com/Miserlou/lambda-packages. I just tested my project that depends on both using the manylinux versions and it works fine on Lambda. I am guessing the same could be done with other packages but would need someone who uses them to test this before removing.

**or**

*B*: have some override flag + logic so that if a package is in both lambda-packages and manylinux wheels to prefer the latter. The only reason this options might work better is for backwards compatibility for anyone who depends on any older versions of packages via lambda-packages.

@Miserlou let me know what might make more sense

**Comment by Miserlou** [comment]
I actually laid out a third alternative here:
https://github.com/Miserlou/lambda-packages/issues/43

We simply change l-p so that it segregates by runtime, that way we can use the Py3 numpy/pscyopg2 from manylinux for P3, but still prefer the lp versions elsewhere. Make sense?

**Comment by nikbora** [comment]
Makes sense. 

I do however think that we should improve the documentation around this. Because even for Python 2.7 runtime you could end up with a situation where if you use psycopg2 2.6.1 you are using l-p (since it has that specific version precompiled) and if you use psycopg2 2.7.1 then you are using wheels. Ideally l-p packages that have wheels versions should be marked for deprecation.

Separately there is now a more pronounced issue of having to download wheels packages on every `zappa update`. For a project with 2+ wheels packages that end up being downloaded each time before being packaged for Lambda it ends up taking a while. But we can tackle that in another issue.

I will create the PR for my Zappa manylinux 3.6 wheels change tomorrow as it doesn't care what ends up happening with l-p.

**Comment by jonatasbaldin** [comment]
Hey, just for info, I'm having the same issue too. If you need any testing, lmk!

**Comment by nikbora** [comment]
Works now with psycopg2 2.7.1 on Zappa 0.41.1.

**Comment by jonatasbaldin** [comment]
I'm using Zappa 0.41.1 and psycopg2 2.7.1 and still getting
`django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: dynamic module does not define module export function (PyInit__psycopg)`

:(

**Comment by nikbora** [comment]
Yeah sorry, I forgot I had a hack to prevent the old lambda-packages version being loaded. If you do this before deploy/update it should force downloading of the proper 2.7.1 package until the lambda-packages changes are merged in:
`echo "lambda_packages = {}" > <wherever_the_virtual_env_is>/lib/python3.6/site-packages/lambda_packages/__init__.py`

**Comment by Miserlou** [comment]
Should be fixed in 0.41.2.

**Comment by blurrcat** [comment]
I'm still getting `No module named 'psycopg2._psycopg'` with zappa==0.41.2 and psycopg2==2.7.1

**Comment by nikbora** [comment]
Is your virtualenv is definitely on python 3.6? Can you check if/what psycopg2 binary version is in the zip after zappa package? (the file name)

**Comment by jneves** [comment]
@nikbora Yes, it's on 3.6.

```$ pip -V
pip 9.0.1 from /Users/joao/projectos/popsss-accounts/ve/lib/python3.6/site-packages (python 3.6)
$ python -V
Python 3.6.1```

File list related to psycopg2 confirms it's 2.7.1:

```$ unzip -vb popsss-accounts-dev-1494419401.zip | grep psycopg2
    4899  Defl:N     2156  56% 01-01-1980 00:00 d21094ca  psycopg2/__init__.py
    2874  Defl:N     1255  56% 01-01-1980 00:00 58eeeed8  psycopg2/_ipaddress.py
    7845  Defl:N     2784  65% 01-01-1980 00:00 75996ad9  psycopg2/_json.py
  465788  Defl:N   153986  67% 01-01-1980 00:00 766fef77  psycopg2/_psycopg.cpython-36m-darwin.so
   17259  Defl:N     4889  72% 01-01-1980 00:00 2b5298b9  psycopg2/_range.py
   13242  Defl:N     4618  65% 01-01-1980 00:00 a17bc872  psycopg2/errorcodes.py
    7020  Defl:N     2848  59% 01-01-1980 00:00 5f5d2d09  psycopg2/extensions.py
   42337  Defl:N    11325  73% 01-01-1980 00:00 922524e3  psycopg2/extras.py
    8173  Defl:N     2376  71% 01-01-1980 00:00 1ccf96ea  psycopg2/pool.py
    3329  Defl:N     1324  60% 01-01-1980 00:00 79f4bb6b  psycopg2/psycopg1.py
   13757  Defl:N     4102  70% 01-01-1980 00:00 6c46e41a  psycopg2/sql.py
    4424  Defl:N     1751  60% 01-01-1980 00:00 99ef9685  psycopg2/tz.py
 1995808  Defl:N   928717  54% 01-01-1980 00:00 9d5fc7e5  psycopg2/.dylibs/libcrypto.1.0.0.dylib
  159072  Defl:N    70805  56% 01-01-1980 00:00 007177b3  psycopg2/.dylibs/libpq.5.8.dylib
  373600  Defl:N   158972  57% 01-01-1980 00:00 3daed09c  psycopg2/.dylibs/libssl.1.0.0.dylib
    3475  Defl:N     1881  46% 01-01-1980 00:00 acda4e21  psycopg2/__pycache__/__init__.cpython-36.pyc
    2041  Defl:N     1124  45% 01-01-1980 00:00 1408f896  psycopg2/__pycache__/_ipaddress.cpython-36.pyc
    6577  Defl:N     3144  52% 01-01-1980 00:00 56f7acf2  psycopg2/__pycache__/_json.cpython-36.pyc
   13934  Defl:N     5921  58% 01-01-1980 00:00 fdef5993  psycopg2/__pycache__/_range.cpython-36.pyc
   11572  Defl:N     4897  58% 01-01-1980 00:00 5d01acf1  psycopg2/__pycache__/errorcodes.cpython-36.pyc
    6405  Defl:N     3429  47% 01-01-1980 00:00 20dd5fba  psycopg2/__pycache__/extensions.cpython-36.pyc
   42099  Defl:N    16650  61% 01-01-1980 00:00 e10378a9  psycopg2/__pycache__/extras.cpython-36.pyc
    6719  Defl:N     2841  58% 01-01-1980 00:00 59a63610  psycopg2/__pycache__/pool.cpython-36.pyc
    2929  Defl:N     1496  49% 01-01-1980 00:00 77f7d7a4  psycopg2/__pycache__/psycopg1.cpython-36.pyc
   13842  Defl:N     5199  62% 01-01-1980 00:00 aa0b4ade  psycopg2/__pycache__/sql.cpython-36.pyc
    4093  Defl:N     2079  49% 01-01-1980 00:00 c5b746ca  psycopg2/__pycache__/tz.cpython-36.pyc
       0  Defl:N        2   0% 05-10-2017 13:30 00000000  psycopg2/__pycache__/__init__.py
    3669  Defl:N     1252  66% 01-01-1980 00:00 d9369d2b  psycopg2/tests/__init__.py
   32278  Defl:N     6607  80% 01-01-1980 00:00 41a9e436  psycopg2/tests/dbapi20.py
    4138  Defl:N      743  82% 01-01-1980 00:00 ebba9d80  psycopg2/tests/dbapi20_tpc.py
   15203  Defl:N     3507  77% 01-01-1980 00:00 af8a06a7  psycopg2/tests/test_async.py
    7386  Defl:N     2229  70% 01-01-1980 00:00 02a94aa4  psycopg2/tests/test_async_keyword.py
    1723  Defl:N      915  47% 01-01-1980 00:00 1117985a  psycopg2/tests/test_bug_gc.py
    1739  Defl:N      838  52% 01-01-1980 00:00 d81b8a7b  psycopg2/tests/test_bugX000.py
    3791  Defl:N     1419  63% 01-01-1980 00:00 0f1e650f  psycopg2/tests/test_cancel.py
   54698  Defl:N     8001  85% 01-01-1980 00:00 b9785e0f  psycopg2/tests/test_connection.py
   11986  Defl:N     3084  74% 01-01-1980 00:00 a5fbe81a  psycopg2/tests/test_copy.py
   20903  Defl:N     4768  77% 01-01-1980 00:00 0135db9e  psycopg2/tests/test_cursor.py
   26610  Defl:N     4344  84% 01-01-1980 00:00 168a9a1e  psycopg2/tests/test_dates.py
    2201  Defl:N     1047  52% 01-01-1980 00:00 00ecc8ba  psycopg2/tests/test_errcodes.py
   17483  Defl:N     2853  84% 01-01-1980 00:00 6252e8a3  psycopg2/tests/test_extras_dictcursor.py
    9359  Defl:N     1658  82% 01-01-1980 00:00 903aaf45  psycopg2/tests/test_fast_executemany.py
    4225  Defl:N     1717  59% 01-01-1980 00:00 8e83a736  psycopg2/tests/test_green.py
    4753  Defl:N     1166  76% 01-01-1980 00:00 6b9145c0  psycopg2/tests/test_ipaddress.py
   15213  Defl:N     3094  80% 01-01-1980 00:00 17ca3089  psycopg2/tests/test_lobject.py
   11749  Defl:N     2911  75% 01-01-1980 00:00 d3cb9d0d  psycopg2/tests/test_module.py
    7943  Defl:N     2140  73% 01-01-1980 00:00 1fe02418  psycopg2/tests/test_notify.py
    2991  Defl:N     1309  56% 01-01-1980 00:00 2107e8a1  psycopg2/tests/test_psycopg2_dbapi20.py
    9379  Defl:N     2675  72% 01-01-1980 00:00 b4530ff0  psycopg2/tests/test_quote.py
    7747  Defl:N     2074  73% 01-01-1980 00:00 ff8c1e48  psycopg2/tests/test_replication.py
   14726  Defl:N     2642  82% 01-01-1980 00:00 dda416b2  psycopg2/tests/test_sql.py
    9244  Defl:N     2262  76% 01-01-1980 00:00 ce134d15  psycopg2/tests/test_transaction.py
   19780  Defl:N     4239  79% 01-01-1980 00:00 1e74886e  psycopg2/tests/test_types_basic.py
   63712  Defl:N    10470  84% 01-01-1980 00:00 5069e7fb  psycopg2/tests/test_types_extras.py
    7389  Defl:N     1671  77% 01-01-1980 00:00 b43595ac  psycopg2/tests/test_with.py
    1431  Defl:N      562  61% 01-01-1980 00:00 aa08e9ff  psycopg2/tests/testconfig.py
   14556  Defl:N     4034  72% 01-01-1980 00:00 d2428151  psycopg2/tests/testutils.py
    2410  Defl:N     1212  50% 01-01-1980 00:00 ababbd74  psycopg2/tests/__pycache__/__init__.cpython-36.pyc
   22322  Defl:N     7961  64% 01-01-1980 00:00 cd236971  psycopg2/tests/__pycache__/dbapi20.cpython-36.pyc
    4361  Defl:N     1515  65% 01-01-1980 00:00 c758f0b4  psycopg2/tests/__pycache__/dbapi20_tpc.cpython-36.pyc
   12921  Defl:N     4733  63% 01-01-1980 00:00 3868b60a  psycopg2/tests/__pycache__/test_async.cpython-36.pyc
    7423  Defl:N     3236  56% 01-01-1980 00:00 573a593e  psycopg2/tests/__pycache__/test_async_keyword.cpython-36.pyc
    1305  Defl:N      786  40% 01-01-1980 00:00 497f5bd1  psycopg2/tests/__pycache__/test_bug_gc.cpython-36.pyc
    1215  Defl:N      650  47% 01-01-1980 00:00 cdf3fdc9  psycopg2/tests/__pycache__/test_bugX000.cpython-36.pyc
    3105  Defl:N     1619  48% 01-01-1980 00:00 9aa20d43  psycopg2/tests/__pycache__/test_cancel.cpython-36.pyc
   44700  Defl:N    13346  70% 01-01-1980 00:00 188d1401  psycopg2/tests/__pycache__/test_connection.cpython-36.pyc
   12725  Defl:N     5095  60% 01-01-1980 00:00 9c473f90  psycopg2/tests/__pycache__/test_copy.cpython-36.pyc
   17255  Defl:N     6680  61% 01-01-1980 00:00 25d89e39  psycopg2/tests/__pycache__/test_cursor.cpython-36.pyc
   26795  Defl:N     7462  72% 01-01-1980 00:00 b4c887d8  psycopg2/tests/__pycache__/test_dates.cpython-36.pyc
    1594  Defl:N     1001  37% 01-01-1980 00:00 d4e1f010  psycopg2/tests/__pycache__/test_errcodes.cpython-36.pyc
   22296  Defl:N     5829  74% 01-01-1980 00:00 2bddc28f  psycopg2/tests/__pycache__/test_extras_dictcursor.cpython-36.pyc
   11350  Defl:N     3053  73% 01-01-1980 00:00 529d4c92  psycopg2/tests/__pycache__/test_fast_executemany.cpython-36.pyc
    3604  Defl:N     1749  52% 01-01-1980 00:00 1874da3d  psycopg2/tests/__pycache__/test_green.cpython-36.pyc
    4300  Defl:N     1574  63% 01-01-1980 00:00 c5686814  psycopg2/tests/__pycache__/test_ipaddress.cpython-36.pyc
   16230  Defl:N     5096  69% 01-01-1980 00:00 5050e6ff  psycopg2/tests/__pycache__/test_lobject.cpython-36.pyc
   11871  Defl:N     4604  61% 01-01-1980 00:00 41f95305  psycopg2/tests/__pycache__/test_module.cpython-36.pyc
    7104  Defl:N     3154  56% 01-01-1980 00:00 b4c9b244  psycopg2/tests/__pycache__/test_notify.cpython-36.pyc
    2047  Defl:N     1099  46% 01-01-1980 00:00 d590088b  psycopg2/tests/__pycache__/test_psycopg2_dbapi20.cpython-36.pyc
    8292  Defl:N     3556  57% 01-01-1980 00:00 8783552d  psycopg2/tests/__pycache__/test_quote.cpython-36.pyc
    6624  Defl:N     2812  58% 01-01-1980 00:00 248860b5  psycopg2/tests/__pycache__/test_replication.cpython-36.pyc
   16521  Defl:N     4658  72% 01-01-1980 00:00 95d167a7  psycopg2/tests/__pycache__/test_sql.cpython-36.pyc
    7386  Defl:N     2766  63% 01-01-1980 00:00 20581972  psycopg2/tests/__pycache__/test_transaction.cpython-36.pyc
   21042  Defl:N     7313  65% 01-01-1980 00:00 b6e660b4  psycopg2/tests/__pycache__/test_types_basic.cpython-36.pyc
   58032  Defl:N    18876  68% 01-01-1980 00:00 dc32dbc0  psycopg2/tests/__pycache__/test_types_extras.cpython-36.pyc
    7693  Defl:N     2711  65% 01-01-1980 00:00 1c7c2420  psycopg2/tests/__pycache__/test_with.cpython-36.pyc
    1170  Defl:N      697  40% 01-01-1980 00:00 f67740d5  psycopg2/tests/__pycache__/testconfig.cpython-36.pyc
   15531  Defl:N     5965  62% 01-01-1980 00:00 a2cc36af  psycopg2/tests/__pycache__/testutils.cpython-36.pyc
       0  Defl:N        2   0% 05-10-2017 13:30 00000000  psycopg2/tests/__pycache__/__init__.py
    2262  Defl:N     1084  52% 01-01-1980 00:00 29257cce  psycopg2-2.7.1.dist-info/DESCRIPTION.rst
       4  Defl:N        6 -50% 01-01-1980 00:00 c2971fc7  psycopg2-2.7.1.dist-info/INSTALLER
    3645  Defl:N     1493  59% 01-01-1980 00:00 c56f9901  psycopg2-2.7.1.dist-info/METADATA
    1428  Defl:N      597  58% 01-01-1980 00:00 bbb15f7b  psycopg2-2.7.1.dist-info/metadata.json
    6763  Defl:N     2689  60% 01-01-1980 00:00 a1fd2ab4  psycopg2-2.7.1.dist-info/RECORD
       9  Defl:N       11 -22% 01-01-1980 00:00 f38589ce  psycopg2-2.7.1.dist-info/top_level.txt
     252  Defl:N      130  48% 01-01-1980 00:00 c751cc40  psycopg2-2.7.1.dist-info/WHEEL
   25916  Defl:N     7954  69% 01-01-1980 00:00 607d2cf2  sqlalchemy/dialects/postgresql/psycopg2.py
    1651  Defl:N      775  53% 01-01-1980 00:00 cade8e62  sqlalchemy/dialects/postgresql/psycopg2cffi.py```

My current work-around is using the statically compiled 3.6 version at https://github.com/jkehler/awslambda-psycopg2

Only reference I could find that might explain this error would be a 32/64 bit architecture mismatch, but not sure how I can test that.

**Comment by nikbora** [comment]
Interesting.

I can reproduce.

Clean virtual env:

```
unzip -vb <>.zip | grep psycopg2 | grep cpython-36m
  465788  Defl:N   153986  67% 01-01-1980 00:00 766fef77  psycopg2/_psycopg.cpython-36m-darwin.so
````

After my hack for lambda-packages:

```
echo "lambda_packages = {}" > $VIRTUAL_ENV/lib/python3.6/site-packages/lambda_packages/__init__.py
```

```
unzip -vb <>.zip | grep psycopg2 | grep cpython-36m
  465788  Defl:N   153986  67% 01-01-1980 00:00 766fef77  psycopg2/_psycopg.cpython-36m-darwin.so
 1041280  Defl:N   319140  69% 01-01-1980 00:00 8e2c946b  psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so
```

So good news is seems related to the code thinking it had found lambda-packages version when it didn't. I shall debug in a bit, but you are right, definitely still an issue :)

**Comment by blurrcat** [comment]
I think this may be the problem: in Python 3, there's no match for `psycopg2` in lambda-packages; later when we try to pull wheels from pip, `psycopg2` is excluded because of [this line](https://github.com/Miserlou/Zappa/blob/master/zappa/core.py#L507):
```
 for installed_package_name in installed_packages_name_set:
     if installed_package_name not in lambda_packages:  # psycopg2 is in lambda_packages
         wheel_url = self.get_manylinux_wheel(installed_package_name)
```
So the actual version shipped to lambda is the one installed in the virtualenv.

**Comment by nikbora** [comment]
Yeah, there is also no check for the actual package version in either lambda-packages or manylinux bit of code. So in case of manylinux for example it will just get the latest version from PyPi no matter what you have in your virtualenv 😱  

I shall submit a PR to fix this in a bit.

**Comment by nikbora** [comment]
@blurrcat and @jneves need to test more, but seems to work for my local Python 3.6. I shall check 2.7 later. I also took the liberty of updating how progress bars work and added more logging for when lambda-packages and manylinux is being used:

```
Calling package for environment test..
Downloading and installing dependencies..
Using lambda-packages binary for psycopg2 2.6.1
Downloading greenlet-0.4.12-cp36-cp36m-manylinux1_x86_64.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 43.0K/43.0K [00:00<00:00, 1.44MB/s]
Downloading gevent-1.2.1-cp36-cp36m-manylinux1_x86_64.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.86M/1.86M [00:00<00:00, 4.03MB/s]
Packaging project as zip..
```

https://github.com/nikbora/Zappa if you fancy having a test

**Comment by jneves** [comment]
@nikbora not working with psycopg2==2.7.1:

```
$ zappa package
Calling package for environment dev..
Downloading and installing dependencies..
Downloading zope.interface-4.4.0-cp36-cp36m-manylinux1_x86_64.whl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 175K/175K [00:00<00:00, 2.07MB/s]
Downloading coverage-4.3.4-cp36-cp36m-manylinux1_x86_64.whl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 192K/192K [00:00<00:00, 2.09MB/s]
Packaging project as zip..
```

**Comment by nikbora** [comment]
@jneves thanks. I submitted a PR, lemme know if it now works for you on my branch (will need to uninstall/install after you pull).

**Comment by jneves** [comment]
@nikbora Awesome, it works! Thanks!

**Comment by nikbora** [comment]
0.41.3 should have fixed this

**Comment by Bijiabo** [comment]
```
[1505579116083] /var/task/psycopg2/_psycopg.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 505, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 239, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 131, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/var/task/main.py", line 2, in <module>
  import psycopg2
  File "/var/task/psycopg2/__init__.py", line 50, in <module>
  from psycopg2._psycopg import (       # noqa
ImportError: /var/task/psycopg2/_psycopg.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
```
I have some problem like this...

**Comment by diegojancic** [comment]
I'm having this problem in zappa 0.44.3.  I'm only trying to deploy a test django project with basically nothing on it.  This is what I get:

```
[1507245506088] Error loading psycopg2 module: No module named 'psycopg2': ImproperlyConfigured
Traceback (most recent call last):
  File "/var/task/handler.py", line 511, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 239, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 145, in __init__
  wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
  File "/var/task/zappa/ext/django_zappa.py", line 20, in get_django_wsgi
  return get_wsgi_application()
  File "/var/task/django/core/wsgi.py", line 13, in get_wsgi_application
  django.setup(set_prefix=False)
  File "/var/task/django/__init__.py", line 27, in setup
  apps.populate(settings.INSTALLED_APPS)
  File "/var/task/django/apps/registry.py", line 108, in populate
  app_config.import_models()
  File "/var/task/django/apps/config.py", line 202, in import_models
  self.models_module = import_module(models_module_name)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/var/task/django/contrib/auth/models.py", line 4, in <module>
  from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/var/task/django/contrib/auth/base_user.py", line 52, in <module>
  class AbstractBaseUser(models.Model):
  File "/var/task/django/db/models/base.py", line 124, in __new__
  new_class.add_to_class('_meta', Options(meta, app_label))
  File "/var/task/django/db/models/base.py", line 331, in add_to_class
  value.contribute_to_class(cls, name)
  File "/var/task/django/db/models/options.py", line 214, in contribute_to_class
  self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/var/task/django/db/__init__.py", line 33, in __getattr__
  return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/var/task/django/db/utils.py", line 211, in __getitem__
  backend = load_backend(db['ENGINE'])
  File "/var/task/django/db/utils.py", line 115, in load_backend
  return import_module('%s.base' % backend_name)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "/var/task/django/db/backends/postgresql/base.py", line 25, in <module>
  raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
```

And that's only because I have this in `settings.py`:


```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        ...
    }
}
```

**Comment by nikbora** [comment]
I guess you not pip installing psycopg2 in your project venv so it never
gets packaged?

**Comment by Sheepzez** [comment]
I ran across the "No module named 'psycopg2' problem, and resolved it by updating psycopg2 to 2.7.4 from 2.6.1.

**Comment by bendog** [comment]
I've been getting this error intermittently, i'm using pipenv, my packages seem correct, the venv is active, if i pip freeze i can see psycopg2 however for some reason it's not being packaged into the zip with zappa update

pipenv 
```
-i https://pypi.org/simple
--extra-index-url https://pypi.my.domain/
argcomplete==1.9.3
aws-xray-sdk==2.4.2
boto3==1.9.130
botocore==1.12.130
certifi==2019.3.9
cfn-flip==1.2.0
chardet==3.0.4
click==7.0
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.8
jmespath==0.9.3
jsonpickle==1.1
kappa==0.6.0
lambda-packages==0.20.0
omnisyandb==2.1.0
placebo==0.9.0
psycopg2==2.7.4
python-dateutil==2.6.1 ; python_version >= '2.7'
python-slugify==1.2.4
pytz==2019.1
pyyaml==5.1
requests==2.21.0
s3transfer==0.2.0
sentry-sdk==0.7.10
six==1.12.0
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.6
unidecode==1.0.23
urllib3==1.24.1 ; python_version >= '3.4'
werkzeug==0.15.2
wheel==0.33.1
wrapt==1.11.1
wsgi-request-logger==0.4.6
zappa==0.48.2
```

**Comment by bendog** [comment]
i had tried with `psycopg2-bin`and ran into trouble (always double check your package names), however if you get the package name correct it works!

the following in my `Pipfile` 
```ini
[packages]
psycopg2-binary = "*"
```

**Comment by lukojewel** [comment]
I solved the issue by installing psycopg2-binary

**Comment by adamloving** [comment]
`pipenv install psycopg2-binary` also solved the issue for me, but I have 2 questions. 

1) Is using `psycopg2-binary` suitable for a production environment? Seems like compiled code would be a good thing, but the docs at https://pypi.org/project/psycopg2-binary/ currently read "The binary package is a practical choice for development and testing but in production it is advised to use the package built from sources."

2) If it is necessary for Django to work in a lambda using Zappa, should `psycopg2-binary` be added (or verified) as a dependency in the `zappa init` command. That would've saved me time tracking this down.

**Comment by oxbits** [comment]
`psycopg2-binary` worked for me.

i was having this issue:

`RuntimeError: populate() isn't reentrant`

https://github.com/Miserlou/Zappa/issues/324

thank you!

**Comment by anhphamt** [comment]
Use this package worked for me
https://github.com/jkehler/awslambda-psycopg2

**Comment by nttrung143** [comment]
I encountered the same problem today while running Zappa on my Mac. I executed the command `pip install psycopg2-binary` again, and everything worked fine.
